-- Tipos de Museo
INSERT INTO TIPOSMUSEO (IDTIPOMUSEO, NOMBRE) VALUES (1, 'Arte');
INSERT INTO TIPOSMUSEO (IDTIPOMUSEO, NOMBRE) VALUES (2, 'Historia');
INSERT INTO TIPOSMUSEO (IDTIPOMUSEO, NOMBRE) VALUES (3, 'Musical');
INSERT INTO TIPOSMUSEO (IDTIPOMUSEO, NOMBRE) VALUES (4, 'Militar');

-- Tipos de Tarjeta
INSERT INTO TIPOSTARJETA (IDTIPOTARJETA, NOMBRE) VALUES (1, 'VISA');
INSERT INTO TIPOSTARJETA (IDTIPOTARJETA, NOMBRE) VALUES (2, 'Mastercard');
INSERT INTO TIPOSTARJETA (IDTIPOTARJETA, NOMBRE) VALUES (3, 'American Express');
INSERT INTO TIPOSTARJETA (IDTIPOTARJETA, NOMBRE) VALUES (4, 'Dinner Club');
INSERT INTO TIPOSTARJETA (IDTIPOTARJETA, NOMBRE) VALUES (5, 'Union Pay');

-- Épocas base para Especies y Temáticas
INSERT INTO EPOCAS (IDEPOCA, NOMBRE, DESCRIPCION) VALUES (1, 'Jurásico', 'Periodo de la era Mesozoica');
INSERT INTO EPOCAS (IDEPOCA, NOMBRE, DESCRIPCION) VALUES (2, 'Cretácico', 'Último periodo de los dinosaurios');
INSERT INTO EPOCAS (IDEPOCA, NOMBRE, DESCRIPCION) VALUES (3, 'Edad Media', 'Época de castillos y reinos');
INSERT INTO EPOCAS (IDEPOCA, NOMBRE, DESCRIPCION) VALUES (4, 'Edad Moderna', 'Renacimiento y revolución industrial');

COMMIT;
