
-- ======================================
-- PROYECTO MAHN 3.0 - SCRIPT UNIFICADO
-- Crear toda la base de datos en Oracle
-- ======================================

-- ===============================
-- 1. CREACIÓN DE TABLAS
-- ===============================

CREATE TABLE TiposMuseo (
    idTipoMuseo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
);

CREATE TABLE Museos (
    idMuseo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    tipoMuseoId NUMBER,
    ubicacion VARCHAR2(100),
    direccion VARCHAR2(255),
    telefono VARCHAR2(50),
    fechaFundacion DATE,
    nombreDirector VARCHAR2(100),
    sitioWeb VARCHAR2(200),
    FOREIGN KEY (tipoMuseoId) REFERENCES TiposMuseo(idTipoMuseo)
);

CREATE TABLE Salas (
    idSala NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(200),
    museoId NUMBER,
    FOREIGN KEY (museoId) REFERENCES Museos(idMuseo)
);

CREATE TABLE Colecciones (
    idColeccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    siglo VARCHAR2(10),
    observacion VARCHAR2(200),
    salaId NUMBER,
    FOREIGN KEY (salaId) REFERENCES Salas(idSala)
);

CREATE TABLE Epocas (
    idEpoca NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    descripcion VARCHAR2(200)
);

CREATE TABLE Especies (
    idEspecie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreCientifico VARCHAR2(100),
    nombreComun VARCHAR2(100),
    fechaExtincion VARCHAR2(50),
    epocaId NUMBER,
    peso NUMBER(6,2),
    tamano NUMBER(6,2),
    caracteristicas VARCHAR2(200),
    coleccionId NUMBER,
    FOREIGN KEY (epocaId) REFERENCES Epocas(idEpoca),
    FOREIGN KEY (coleccionId) REFERENCES Colecciones(idColeccion)
);

CREATE TABLE Tematicas (
    idTematica NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    caracteristicas VARCHAR2(200),
    epocaId NUMBER,
    salaId NUMBER,
    FOREIGN KEY (epocaId) REFERENCES Epocas(idEpoca),
    FOREIGN KEY (salaId) REFERENCES Salas(idSala)
);

CREATE TABLE Precios (
    idPrecio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    precioLunesASabado NUMBER(5,2),
    precioDomingo NUMBER(5,2),
    salaId NUMBER,
    FOREIGN KEY (salaId) REFERENCES Salas(idSala)
);

CREATE TABLE TiposTarjeta (
    idTipoTarjeta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
);

CREATE TABLE ComisionesTarjetas (
    idComision NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipoTarjetaId NUMBER,
    comision NUMBER(5,3),
    FOREIGN KEY (tipoTarjetaId) REFERENCES TiposTarjeta(idTipoTarjeta)
);

CREATE TABLE Roles (
    idRol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
);

CREATE TABLE Usuarios (
    idUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    correo VARCHAR2(100),
    rolId NUMBER,
    FOREIGN KEY (rolId) REFERENCES Roles(idRol)
);

CREATE TABLE Horarios (
    idHorario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia VARCHAR2(20),
    horaApertura VARCHAR2(10),
    horaCierre VARCHAR2(10),
    museoId NUMBER,
    FOREIGN KEY (museoId) REFERENCES Museos(idMuseo)
);

CREATE TABLE Transacciones (
    idTransaccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE,
    monto NUMBER(8,2),
    tipo VARCHAR2(100),
    usuarioId NUMBER,
    comisionId NUMBER,
    FOREIGN KEY (usuarioId) REFERENCES Usuarios(idUsuario),
    FOREIGN KEY (comisionId) REFERENCES ComisionesTarjetas(idComision)
);

CREATE TABLE Entradas (
    idEntrada NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaVisita DATE,
    precioTotal NUMBER(8,2),
    codigoQR VARCHAR2(200),
    usuarioId NUMBER,
    transaccionId NUMBER,
    FOREIGN KEY (usuarioId) REFERENCES Usuarios(idUsuario),
    FOREIGN KEY (transaccionId) REFERENCES Transacciones(idTransaccion)
);

CREATE TABLE EntradasSalas (
    idEntradaSala NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entradaId NUMBER,
    salaId NUMBER,
    FOREIGN KEY (entradaId) REFERENCES Entradas(idEntrada),
    FOREIGN KEY (salaId) REFERENCES Salas(idSala)
);

CREATE TABLE ValidacionesEntradas (
    idValidacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entradaId NUMBER,
    salaId NUMBER,
    fechaValidacion TIMESTAMP,
    valido CHAR(1),
    FOREIGN KEY (entradaId) REFERENCES Entradas(idEntrada),
    FOREIGN KEY (salaId) REFERENCES Salas(idSala)
);

CREATE TABLE ValoracionesSalas (
    idValoracion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salaId NUMBER,
    valoracion NUMBER(1),
    observacion VARCHAR2(200),
    fecha DATE,
    entradaId NUMBER,
    FOREIGN KEY (salaId) REFERENCES Salas(idSala),
    FOREIGN KEY (entradaId) REFERENCES Entradas(idEntrada)
);

CREATE TABLE PromediosValoraciones (
    idPromedio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salaId NUMBER,
    promedio NUMBER(3,1),
    totalValoraciones NUMBER(5),
    FOREIGN KEY (salaId) REFERENCES Salas(idSala)
);

-- ===============================
-- 2. ALTERACIONES POSTERIORES
-- ===============================

ALTER TABLE ValidacionesEntradas ADD fecha DATE;
ALTER TABLE Usuarios ADD contrasena VARCHAR2(100);

-- ===============================
-- 3. DATOS INICIALES
-- ===============================

-- Tipos de Museo
INSERT INTO TiposMuseo (idTipoMuseo, nombre) VALUES (1, 'Arte');
INSERT INTO TiposMuseo (idTipoMuseo, nombre) VALUES (2, 'Historia');
INSERT INTO TiposMuseo (idTipoMuseo, nombre) VALUES (3, 'Musical');
INSERT INTO TiposMuseo (idTipoMuseo, nombre) VALUES (4, 'Militar');

-- Tipos de Tarjeta
INSERT INTO TiposTarjeta (idTipoTarjeta, nombre) VALUES (1, 'VISA');
INSERT INTO TiposTarjeta (idTipoTarjeta, nombre) VALUES (2, 'Mastercard');
INSERT INTO TiposTarjeta (idTipoTarjeta, nombre) VALUES (3, 'American Express');
INSERT INTO TiposTarjeta (idTipoTarjeta, nombre) VALUES (4, 'Dinner Club');
INSERT INTO TiposTarjeta (idTipoTarjeta, nombre) VALUES (5, 'Union Pay');

-- Épocas (base)
INSERT INTO Epocas (idEpoca, nombre, descripcion) VALUES (1, 'Prehistoria', 'Antes de la escritura');
INSERT INTO Epocas (idEpoca, nombre, descripcion) VALUES (2, 'Edad Antigua', 'Primeras civilizaciones');
INSERT INTO Epocas (idEpoca, nombre, descripcion) VALUES (3, 'Edad Media', 'Imperios y religiones');
INSERT INTO Epocas (idEpoca, nombre, descripcion) VALUES (4, 'Edad Moderna', 'Renacimiento y descubrimientos');
INSERT INTO Epocas (idEpoca, nombre, descripcion) VALUES (5, 'Edad Contemporánea', 'Revoluciones e industrialización');

COMMIT;
